/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/O58QgkEOn2o
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { CarouselItem, CarouselContent, CarouselPrevious, CarouselNext, Carousel } from "@/components/ui/carousel"

export function CarouselPage() {
  return (
    <div className="w-full h-screen relative overflow-hidden">
      <Carousel className="w-full h-full">
        <CarouselContent>
          <CarouselItem>
            <div className="relative h-full w-full overflow-hidden">
              <img
                alt="Imagen 1"
                className="h-full w-full object-cover"
                height="800"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "1920/800",
                  objectFit: "cover",
                }}
                width="1920"
              />
              <div className="absolute inset-0 bg-gradient-to-t from-gray-900/50 to-transparent" />
              <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 text-center text-white px-4 sm:px-6 md:px-10">
                <h3 className="text-3xl sm:text-4xl md:text-5xl font-bold">Título de la imagen 1</h3>
                <p className="mt-4 text-lg sm:text-xl">Descripción breve de la imagen 1</p>
              </div>
            </div>
          </CarouselItem>
          <CarouselItem>
            <div className="relative h-full w-full overflow-hidden">
              <img
                alt="Imagen 2"
                className="h-full w-full object-cover"
                height="800"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "1920/800",
                  objectFit: "cover",
                }}
                width="1920"
              />
              <div className="absolute inset-0 bg-gradient-to-t from-gray-900/50 to-transparent" />
              <div className="absolute bottom-6 left-6 text-white px-4 sm:px-6 md:px-10">
                <h3 className="text-3xl sm:text-4xl md:text-5xl font-bold">Título de la imagen 2</h3>
                <p className="mt-4 text-lg sm:text-xl">Descripción breve de la imagen 2</p>
              </div>
            </div>
          </CarouselItem>
          <CarouselItem>
            <div className="relative h-full w-full overflow-hidden">
              <img
                alt="Imagen 3"
                className="h-full w-full object-cover"
                height="800"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "1920/800",
                  objectFit: "cover",
                }}
                width="1920"
              />
              <div className="absolute inset-0 bg-gradient-to-t from-gray-900/50 to-transparent" />
              <div className="absolute bottom-6 right-6 text-white text-right px-4 sm:px-6 md:px-10">
                <h3 className="text-3xl sm:text-4xl md:text-5xl font-bold">Título de la imagen 3</h3>
                <p className="mt-4 text-lg sm:text-xl">Descripción breve de la imagen 3</p>
              </div>
            </div>
          </CarouselItem>
        </CarouselContent>
        <CarouselPrevious className="absolute left-4 top-1/2 -translate-y-1/2 rounded-full bg-white/50 p-2 text-gray-900 shadow-md transition-colors hover:bg-white sm:left-6 md:left-10">
          <ChevronLeftIcon className="h-6 w-6" />
        </CarouselPrevious>
        <CarouselNext className="absolute right-4 top-1/2 -translate-y-1/2 rounded-full bg-white/50 p-2 text-gray-900 shadow-md transition-colors hover:bg-white sm:right-6 md:right-10">
          <ChevronRightIcon className="h-6 w-6" />
        </CarouselNext>
      </Carousel>
    </div>
  )
}

function ChevronLeftIcon(props : any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m15 18-6-6 6-6" />
    </svg>
  )
}


function ChevronRightIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m9 18 6-6-6-6" />
    </svg>
  )
}
