/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/PQtox9GfL88
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { SelectValue, SelectTrigger, SelectItem, SelectContent, Select } from "@/components/ui/select"
import { Button } from "@/components/ui/button"
import Link from "next/link"
import { Badge } from "@/components/ui/badge"

export function FiltroListadoProductos() {
  return (
    <div className="grid grid-cols-1 md:grid-cols-[280px_1fr] gap-6 p-4 md:p-6">
      
      
      <div className="bg-white rounded-lg shadow-lg overflow-hidden dark:bg-gray-700 p-4 md:p-6">
        <h2 className="text-lg font-semibold mb-8">Filtro</h2>
        <div className="grid gap-4">
          <div className="relative">
            <label
              className="absolute -top-3 left-3 text-sm font-medium text-gray-700 dark:text-gray-400 bg-white dark:bg-gray-700 px-1 z-10"
              htmlFor="price-min"
            >
              Min
            </label>
            <div className="mt-1 relative rounded-md">
              <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                <span className="text-gray-500 sm:text-sm">$</span>
              </div>
              <input
                className="focus:ring-0 focus:border-gray-300 block w-full pl-7 pr-12 sm:text-sm border-gray-300 rounded-md dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 transition-all duration-300 ease-in-out transform focus:scale-105 pt-3 pb-1"
                id="price-min"
                name="price-min"
                placeholder="0.00"
                type="text"
              />
            </div>
          </div>
          <div className="relative">
            <label
              className="absolute -top-3 left-3 text-sm font-medium text-gray-700 dark:text-gray-400 bg-white dark:bg-gray-700 px-1 z-10"
              htmlFor="price-max"
            >
              Max
            </label>
            <div className="mt-1 relative rounded-md">
              <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                <span className="text-gray-500 sm:text-sm">$</span>
              </div>
              <input
                className="focus:ring-0 focus:border-gray-300 block w-full pl-7 pr-12 sm:text-sm border-gray-300 rounded-md dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 transition-all duration-300 ease-in-out transform focus:scale-105 pt-3 pb-1"
                id="price-max"
                name="price-max"
                placeholder="0.00"
                type="text"
              />
            </div>
          </div>
          <div className="relative">
            <label
              className="absolute -top-3 left-3 text-sm font-medium text-gray-700 dark:text-gray-400 bg-white dark:bg-gray-700 px-1 z-10"
              htmlFor="product-name"
            >
              Producto
            </label>
            <div className="mt-1">
              <input
                className="shadow-sm focus:ring-0 focus:border-gray-300 block w-full sm:text-sm border-0 rounded-md dark:bg-gray-800 dark:text-gray-400 transition-all duration-300 ease-in-out transform focus:scale-105 pt-3 pb-1"
                id="product-name"
                name="product-name"
                placeholder="    Busca aqui"
                type="text"
              />
            </div>
          </div>
          <div className="relative">
            <label
              className="absolute -top-3 left-3 text-sm font-medium text-gray-700 dark:text-gray-400 bg-white dark:bg-gray-700 px-1 z-10"
              htmlFor="tags"
            >
              Tags
            </label>
            <div className="mt-1">
              <Select>
                <SelectTrigger id="tags">
                  <SelectValue placeholder="Select tags" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="tag1">Tag 1</SelectItem>
                  <SelectItem value="tag2">Tag 2</SelectItem>
                  <SelectItem value="tag3">Tag 3</SelectItem>
                </SelectContent>
              </Select>
            </div>
          </div>
          <Button className="w-full" size="sm">
            Aplicar filtro
          </Button>
        </div>
      </div>
      <section className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">



        <div className="bg-white rounded-lg shadow-lg overflow-hidden dark:bg-gray-200">
          <div className="relative group">
            <img
              alt="Producto 1"
              className="w-full h-60 object-cover"
              height={300}
              src="/placeholder.svg"
              style={{
                aspectRatio: "400/300",
                objectFit: "cover",
              }}
              width={400}
            />
            <Link className="absolute inset-0 z-10" href="#">
              <span className="sr-only">View</span>
            </Link>
          </div>
          <div className="p-4 flex flex-col gap-4">
            <div>
              <h3 className="text-lg font-semibold">Producto 1</h3>
              <div className="flex items-center gap-2">
                <Badge className="bg-[#4CAF50] text-white" variant="outline">
                  Camiseta
                </Badge>
              </div>
              <p className="text-gray-500 dark:text-gray-400">Descripción del producto 1</p>
              <div className="flex justify-between items-center">
                <p className="text-gray-500 dark:text-gray-400">En stock: 50 unidades</p>
                <p className="text-lg font-semibold">$99.99</p>
              </div>
            </div>
            <div className="flex justify-between gap-2">
              <Button
                className="bg-[#4CAF50] text-white hover:bg-[#45a049] dark:bg-[#4CAF50] dark:text-white dark:hover:bg-[#45a049]"
                size="sm"
                variant="outline"
              >
                Agregar al carrito
              </Button>
              <Link
                className="inline-flex h-8 items-center justify-center rounded-md bg-[#008CBA] px-4 text-sm font-medium text-white shadow transition-colors hover:bg-[#006D9C] focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-[#006D9C] disabled:pointer-events-none disabled:opacity-50 dark:bg-[#008CBA] dark:hover:bg-[#006D9C] dark:focus-visible:ring-[#006D9C]"
                href="/producto-unos"
              >
                Ver producto
              </Link>
            </div>
          </div>
        </div>



        <div className="bg-white rounded-lg shadow-lg overflow-hidden dark:bg-gray-300">
          <div className="relative group">
            <img
              alt="Producto 2"
              className="w-full h-60 object-cover"
              height={300}
              src="/placeholder.svg"
              style={{
                aspectRatio: "400/300",
                objectFit: "cover",
              }}
              width={400}
            />
            <Link className="absolute inset-0 z-10" href="#">
              <span className="sr-only">View</span>
            </Link>
          </div>
          <div className="p-4 flex flex-col gap-4">
            <div>
              <h3 className="text-lg font-semibold">Producto 2</h3>
              <div className="flex items-center gap-2">
                <Badge className="bg-[#FFC107] text-white" variant="outline">
                  Llavero
                </Badge>
              </div>
              <p className="text-gray-500 dark:text-gray-400">Descripción del producto 2</p>
              <div className="flex justify-between items-center">
                <p className="text-gray-500 dark:text-gray-400">En stock: 25 unidades</p>
                <p className="text-lg font-semibold">$49.99</p>
              </div>
            </div>
            <div className="flex justify-between gap-2">
              <Button
                className="bg-[#4CAF50] text-white hover:bg-[#45a049] dark:bg-[#4CAF50] dark:text-white dark:hover:bg-[#45a049]"
                size="sm"
                variant="outline"
              >
                Agregar al carrito
              </Button>
              <Link
                className="inline-flex h-8 items-center justify-center rounded-md bg-[#008CBA] px-4 text-sm font-medium text-white shadow transition-colors hover:bg-[#006D9C] focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-[#006D9C] disabled:pointer-events-none disabled:opacity-50 dark:bg-[#008CBA] dark:hover:bg-[#006D9C] dark:focus-visible:ring-[#006D9C]"
                href="#"
              >
                Ver producto
              </Link>
            </div>
          </div>
        </div>


        <div className="bg-white rounded-lg shadow-lg overflow-hidden dark:bg-gray-400">
          <div className="relative group">
            <img
              alt="Producto 3"
              className="w-full h-60 object-cover"
              height={300}
              src="/placeholder.svg"
              style={{
                aspectRatio: "400/300",
                objectFit: "cover",
              }}
              width={400}
            />
            <Link className="absolute inset-0 z-10" href="#">
              <span className="sr-only">View</span>
            </Link>
          </div>
          <div className="p-4 flex flex-col gap-4">
            <div>
              <h3 className="text-lg font-semibold">Producto 3</h3>
              <div className="flex items-center gap-2">
                <Badge className="bg-[#E91E63] text-white" variant="outline">
                  Figura
                </Badge>
              </div>
              <p className="text-gray-500 dark:text-gray-400">Descripción del producto 3</p>
              <div className="flex justify-between items-center">
                <p className="text-gray-500 dark:text-gray-400">En stock: 100 unidades</p>
                <p className="text-lg font-semibold">$79.99</p>
              </div>
            </div>
            <div className="flex justify-between gap-2">
              <Button
                className="bg-[#4CAF50] text-white hover:bg-[#45a049] dark:bg-[#4CAF50] dark:text-white dark:hover:bg-[#45a049]"
                size="sm"
                variant="outline"
              >
                Agregar al carrito
              </Button>
              <Link
                className="inline-flex h-8 items-center justify-center rounded-md bg-[#008CBA] px-4 text-sm font-medium text-white shadow transition-colors hover:bg-[#006D9C] focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-[#006D9C] disabled:pointer-events-none disabled:opacity-50 dark:bg-[#008CBA] dark:hover:bg-[#006D9C] dark:focus-visible:ring-[#006D9C]"
                href="#"
              >
                Ver producto
              </Link>
            </div>
          </div>
        </div>


        <div className="bg-white rounded-lg shadow-lg overflow-hidden dark:bg-gray-500">
          <div className="relative group">
            <img
              alt="Producto 4"
              className="w-full h-60 object-cover"
              height={300}
              src="/placeholder.svg"
              style={{
                aspectRatio: "400/300",
                objectFit: "cover",
              }}
              width={400}
            />
            <Link className="absolute inset-0 z-10" href="#">
              <span className="sr-only">View</span>
            </Link>
          </div>

          <div className="p-4 flex flex-col gap-4">
            <div>
              <h3 className="text-lg font-semibold">Producto 4</h3>
              <div className="flex items-center gap-2">
                <Badge className="bg-[#673AB7] text-white" variant="outline">
                  Taza
                </Badge>
              </div>
              <p className="text-gray-500 dark:text-gray-400">Descripción del producto 4</p>
              <div className="flex justify-between items-center">
                <p className="text-gray-500 dark:text-gray-400">En stock: 75 unidades</p>
                <p className="text-lg font-semibold">$59.99</p>
              </div>
            </div>
            <div className="flex justify-between gap-2">
              <Button
                className="bg-[#4CAF50] text-white hover:bg-[#45a049] dark:bg-[#4CAF50] dark:text-white dark:hover:bg-[#45a049]"
                size="sm"
                variant="outline"
              >
                Agregar al carrito
              </Button>
              <Link
                className="inline-flex h-8 items-center justify-center rounded-md bg-[#008CBA] px-4 text-sm font-medium text-white shadow transition-colors hover:bg-[#006D9C] focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-[#006D9C] disabled:pointer-events-none disabled:opacity-50 dark:bg-[#008CBA] dark:hover:bg-[#006D9C] dark:focus-visible:ring-[#006D9C]"
                href="#"
              >
                Ver producto
              </Link>
            </div>
          </div>
        </div>

        <div className="bg-white rounded-lg shadow-lg overflow-hidden dark:bg-gray-600">
          <div className="relative group">
            <img
              alt="Producto 4"
              className="w-full h-60 object-cover"
              height={300}
              src="/placeholder.svg"
              style={{
                aspectRatio: "400/300",
                objectFit: "cover",
              }}
              width={400}
            />
            <Link className="absolute inset-0 z-10" href="#">
              <span className="sr-only">View</span>
            </Link>
          </div>

          <div className="p-4 flex flex-col gap-4">
            <div>
              <h3 className="text-lg font-semibold">Producto 4</h3>
              <div className="flex items-center gap-2">
                <Badge className="bg-[#673AB7] text-white" variant="outline">
                  Taza
                </Badge>
              </div>
              <p className="text-gray-500 dark:text-gray-400">Descripción del producto 4</p>
              <div className="flex justify-between items-center">
                <p className="text-gray-500 dark:text-gray-400">En stock: 75 unidades</p>
                <p className="text-lg font-semibold">$59.99</p>
              </div>
            </div>
            <div className="flex justify-between gap-2">
              <Button
                className="bg-[#4CAF50] text-white hover:bg-[#45a049] dark:bg-[#4CAF50] dark:text-white dark:hover:bg-[#45a049]"
                size="sm"
                variant="outline"
              >
                Agregar al carrito
              </Button>
              <Link
                className="inline-flex h-8 items-center justify-center rounded-md bg-[#008CBA] px-4 text-sm font-medium text-white shadow transition-colors hover:bg-[#006D9C] focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-[#006D9C] disabled:pointer-events-none disabled:opacity-50 dark:bg-[#008CBA] dark:hover:bg-[#006D9C] dark:focus-visible:ring-[#006D9C]"
                href="#"
              >
                Ver producto
              </Link>
            </div>
          </div>
        </div>

        <div className="bg-white rounded-lg shadow-lg overflow-hidden dark:bg-gray-700">
          <div className="relative group">
            <img
              alt="Producto 4"
              className="w-full h-60 object-cover"
              height={300}
              src="/placeholder.svg"
              style={{
                aspectRatio: "400/300",
                objectFit: "cover",
              }}
              width={400}
            />
            <Link className="absolute inset-0 z-10" href="#">
              <span className="sr-only">View</span>
            </Link>
          </div>
          <div className="p-4 flex flex-col gap-4">
            <div>
              <h3 className="text-lg font-semibold">Producto 4</h3>
              <div className="flex items-center gap-2">
                <Badge className="bg-[#673AB7] text-white" variant="outline">
                  Taza
                </Badge>
              </div>
              <p className="text-gray-500 dark:text-gray-400">Descripción del producto 4</p>
              <div className="flex justify-between items-center">
                <p className="text-gray-500 dark:text-gray-400">En stock: 75 unidades</p>
                <p className="text-lg font-semibold">$59.99</p>
              </div>
            </div>
            <div className="flex justify-between gap-2">
              <Button
                className="bg-[#4CAF50] text-white hover:bg-[#45a049] dark:bg-[#4CAF50] dark:text-white dark:hover:bg-[#45a049]"
                size="sm"
                variant="outline"
              >
                Agregar al carrito
              </Button>
              <Link
                className="inline-flex h-8 items-center justify-center rounded-md bg-[#008CBA] px-4 text-sm font-medium text-white shadow transition-colors hover:bg-[#006D9C] focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-[#006D9C] disabled:pointer-events-none disabled:opacity-50 dark:bg-[#008CBA] dark:hover:bg-[#006D9C] dark:focus-visible:ring-[#006D9C]"
                href="#"
              >
                Ver producto
              </Link>
            </div>
          </div>
        </div>

        <div className="bg-white rounded-lg shadow-lg overflow-hidden dark:bg-gray-800">
          <div className="relative group">
            <img
              alt="Producto 4"
              className="w-full h-60 object-cover"
              height={300}
              src="/placeholder.svg"
              style={{
                aspectRatio: "400/300",
                objectFit: "cover",
              }}
              width={400}
            />
            <Link className="absolute inset-0 z-10" href="#">
              <span className="sr-only">View</span>
            </Link>
          </div>
          <div className="p-4 flex flex-col gap-4">
            <div>
              <h3 className="text-lg font-semibold">Producto 4</h3>
              <div className="flex items-center gap-2">
                <Badge className="bg-[#673AB7] text-white" variant="outline">
                  Taza
                </Badge>
              </div>
              <p className="text-gray-500 dark:text-gray-400">Descripción del producto 4</p>
              <div className="flex justify-between items-center">
                <p className="text-gray-500 dark:text-gray-400">En stock: 75 unidades</p>
                <p className="text-lg font-semibold">$59.99</p>
              </div>
            </div>
            <div className="flex justify-between gap-2">
              <Button
                className="bg-[#4CAF50] text-white hover:bg-[#45a049] dark:bg-[#4CAF50] dark:text-white dark:hover:bg-[#45a049]"
                size="sm"
                variant="outline"
              >
                Agregar al carrito
              </Button>
              <Link
                className="inline-flex h-8 items-center justify-center rounded-md bg-[#008CBA] px-4 text-sm font-medium text-white shadow transition-colors hover:bg-[#006D9C] focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-[#006D9C] disabled:pointer-events-none disabled:opacity-50 dark:bg-[#008CBA] dark:hover:bg-[#006D9C] dark:focus-visible:ring-[#006D9C]"
                href="#"
              >
                Ver producto
              </Link>
            </div>
          </div>
        </div>

      </section>
    </div>
  )
}
