/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/QhCCIYwi1HJ
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Eczar } from 'next/font/google'
import { Yeseva_One } from 'next/font/google'

eczar({
  subsets: ['latin'],
  display: 'swap',
})

yeseva_one({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Badge } from "@/components/ui/badge"
import { Label } from "@/components/ui/label"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"

export function ProductoTres() {
  return (
    <div className="grid md:grid-cols-2 gap-6 lg:gap-12 items-start max-w-6xl px-4 mx-auto py-6">
      <div className="grid gap-4 md:gap-10 items-start">
        <img
          alt="Product Image"
          className="aspect-[2/3] object-cover border border-gray-200 w-full rounded-lg overflow-hidden dark:border-gray-800 dark:border-gray-800"
          height={900}
          src="/placeholder.svg"
          width={600}
        />
      </div>
      <div className="grid gap-4 md:gap-10 items-start">
        <div className="grid gap-2">
          <div className="flex items-center gap-2">
            <Badge className="bg-gray-900/10 text-gray-900 dark:bg-gray-900/20 dark:text-gray-900 dark:bg-gray-50/10 dark:text-gray-50 dark:dark:bg-gray-50/20 dark:dark:text-gray-50">Nuevo!</Badge>
            <Badge className="bg-success/10 text-success dark:bg-success/20 dark:text-success">Polera hombre</Badge>
            <Badge className="bg-success/10 text-success dark:bg-success/20 dark:text-success">One pice</Badge>
          </div>
          <h1 className="font-bold text-3xl lg:text-4xl">Polera One Pice</h1>
        </div>
        <div className="grid gap-4">
          <div className="text-sm leading-loose text-gray-500 dark:text-gray-400">
            <p>
              kjhdshd dkjdasjkhas dhdkjhd dakjah dkhad dkjhad  kasjh adkjh d kajsh kajshd kajhasd kdjh kjahs kjahs kjahsd kjahs dkjhd jhakjhd kjash kajsdh askdjh
            </p>
            <p>
              Tkjhdshd dkjdasjkhas dhdasasd  kasjh adkjh dasasaskdjh kjahs kjahs kjaadsassd kjash kajsdh askdjh
            </p>
          </div>
          <div className="flex items-center gap-4">
            <div className="text-4xl font-bold">$100</div>
            <div className="flex items-center gap-2">
              <StarIcon className="w-5 h-5 fill-gray-900 dark:fill-gray-50" />
              <StarIcon className="w-5 h-5 fill-gray-900 dark:fill-gray-50" />
              <StarIcon className="w-5 h-5 fill-gray-900 dark:fill-gray-50" />
              <StarIcon className="w-5 h-5 fill-gray-100 stroke-gray-500 dark:fill-gray-800 dark:stroke-gray-400" />
              <StarIcon className="w-5 h-5 fill-gray-100 stroke-gray-500 dark:fill-gray-800 dark:stroke-gray-400" />
            </div>
          </div>
          <div className="grid gap-4">
            <div className="grid gap-2">
              <Label className="text-base" htmlFor="quantity">
                Cantidad
              </Label>
              <div className="flex items-center gap-2">
                <Button size="icon" variant="outline">
                  <MinusIcon className="h-4 w-4" />
                </Button>
                <Input className="w-16 text-center" defaultValue={1} id="quantity" type="number" />
                <Button size="icon" variant="outline">
                  <PlusIcon className="h-4 w-4" />
                </Button>
              </div>
            </div>
            <Button size="lg">Agregar al carrito</Button>
          </div>
        </div>
      </div>
    </div>
  )
}

function MinusIcon(props : any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
    </svg>
  )
}


function PlusIcon(props : any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
      <path d="M12 5v14" />
    </svg>
  )
}


function StarIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2" />
    </svg>
  )
}
